eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 9000
feign:
  hystrix:
    enabled: true
spring:
  boot:
    admin:
      client:
        # server地址
        url: http://localhost:8679
        instance:
          #client地址
          service-base-url: http://localhost:${server.port}
          #默认为true 开启springboot admin
        enabled: true
  application:
    name: gateway-service
  redis:
    host: 127.0.0.1
    port: 6379
    #password: 123456
    database: 0
  cloud:
    gateway:
      routes:
        - id: user_route
#          uri: https://baidu.com
          uri: lb://user-service
          predicates:
            - Path=/user-server/**
          filters:
            - StripPrefix=1
        - id: order_route
          uri: lb://order-service
          predicates:
            - Path=/order-server/**
          filters:
          - StripPrefix=1
          - name: RequestRateLimiter
            args:
              #用于限流的键的解析器的 Bean 对象的名字,使用 SpEL 表达式根据#{@beanName}获取Bean对象
              key-resolver: '#{@remoteAddrKeyResolver}'
              # 每秒最大访问次数
              redis-rate-limiter.replenishRate: 1
              #令牌桶总容量
              redis-rate-limiter.burstCapacity: 3

#Actuator配置：暴露敏感路径，默认情况下，敏感路径并不暴露
management:
  endpoints:
    web:
      exposure:
        # 暴露xxx端点，如需暴露多个，用,分隔；如需暴露所有端点，用'*'
        include: "*"
  endpoint:
    health:
      # 是否展示健康检查详情
      show-details: ALWAYS

# info信息会显示到SpringBootAdmin的server端，这里取的是pom文件中的数据
info:
  version: @project.version@
  groupId: @project.groupId@
  artifactId: @project.artifactId@