server:
  port: 8763
spring:
  boot:
    admin:
      client:
        # server地址
        url: http://localhost:8679
        instance:
          #client地址
          service-base-url: http://localhost:${server.port}
          #默认为true 开启springboot admin
        enabled: true
  application:
    name: user-service
  datasource:
    name: test
    url: jdbc:mysql://114.55.27.239:3306/sygl?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&allowMultiQueries=true&useSSL=false&zeroDateTimeBehavior=convertToNull
    username: root
    password: 565977989
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
  redis:
    host: 127.0.0.1
    #redis密码，没有密码的可以用～表示
    password:
    port: 6379
    jedis:
      pool:
        max-idle: 100
        max-wait:

mybatis:
  type-aliases-package: com.example.userserver.mapper
  mapper-locations: classpath:mapper/*.xml
  configLocation: classpath:mybatis-config.xml

feign:
  hystrix:
    enabled: true

#Actuator配置：暴露敏感路径，默认情况下，敏感路径并不暴露
management:
  endpoints:
    web:
      exposure:
        # 暴露xxx端点，如需暴露多个，用,分隔；如需暴露所有端点，用'*'
        include: "*"
  endpoint:
    health:
      # 是否展示健康检查详情
      show-details: ALWAYS

# info信息会显示到SpringBootAdmin的server端，这里取的是pom文件中的数据
info:
  version: @project.version@
  groupId: @project.groupId@
  artifactId: @project.artifactId@