server:
  port: 9000

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: zuul-service

zuul:
  host:
    connect-timeout-millis: 60000
    socket-timeout-millis: 60000
  routes:
    user-route:
      path: /user-server/**
      serviceId: user-service
    client-route:
      path: /client-server/**
      serviceId: client-service
