eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 2222
spring:
  application:
    name: client-service
feign:
  hystrix:
    enabled: true # ¿ªÆôFeignÈÛ¶Ï