eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 2222
spring:
  boot:
    admin:
      client:
        # server地址
        url: http://localhost:8679
        instance:
          #client地址
          service-base-url: http://localhost:${server.port}
        #默认为true 开启springboot admin
        enabled: true
  application:
    name: order-service
feign:
  hystrix:
    enabled: true

#Actuator配置：暴露敏感路径，默认情况下，敏感路径并不暴露
management:
  endpoints:
    web:
      exposure:
        # 暴露xxx端点，如需暴露多个，用,分隔；如需暴露所有端点，用'*'
        include: "*"
  endpoint:
    health:
      # 是否展示健康检查详情
      show-details: ALWAYS

# info信息会显示到SpringBootAdmin的server端，这里取的是pom文件中的数据
info:
  version: "@project.version@"
  groupId: "@project.groupId@"
  artifactId: "@project.artifactId@"